### PR TITLE
fix: Fallback to using system installed rust-analyzer

### PR DESCRIPTION
**Pull request by trygveaa**
If rust-analyzer is not available in the storage path or in the configured server path, check if it's available in PATH and use that if it is.

### CODE REVIEW

**Comment by fannheyward** [comment]
Set `"rust-analyzer.server.path": "rust-analyzer"` will resolve rust-analyzer from your PATH.

There're two options on `rust-analyzer.server.path`:

1. if set, resolving it from PATH to use, without downloading from GitHub and updating
2. if not, coc-rust-analyzer will download and update it from GitHub

So, no need to add more checks.

**Comment by trygveaa** [comment]
> Set `"rust-analyzer.server.path": "rust-analyzer"` will resolve rust-analyzer from your PATH.

It's more practical with software that just works out of the box without having to configure it in my opinion. Additionally, it says "Rust Analyzer is not found" by default even when it's installed system wide, which can be confusing. I see there's several closed issues about this, so why not make it easier for people?

**Comment by fannheyward** [comment]
Yes, coc-rust-analyzer used to fallback to system installed RA if not found in bundled or server.path, but I've removed this checking: system installed RA _always_ outdated, this caused many compatible issues because RA updates very fast with breaking changes in earlier versions. I've removed this checking to make coc-rust-analyzer to check RA from GitHub, make sure we're always using the latest release.

**Comment by trygveaa** [comment]
Okay, I see. What if instead of disabling update checking when system installed rust-analyzer is detected (as I did here), we instead check the version of the system installed one, and ask to install the latest if it's an older version?

We'd have to parse the output from `rust-analyzer --version`, but can just show a warning and ask to install latest if the output is in an unexpected format.

(Fwiw, my system installed rust-analyzer is the latest version)

**Comment by fannheyward** [comment]
Will work on this next week, sorry for the delay.

**Pull request merged**
