### PR TITLE
feat(cmds): support snippet text edit

### PR DESCRIPTION
**Pull request by fannheyward**
https://github.com/rust-analyzer/rust-analyzer/pull/4494

@oblitum @TimoFreiberg can you guys test this? Maybe you need to download latest nightly release.

### CODE REVIEW

**Comment by TimoFreiberg** [comment]
I'll try it :)
Do I understand correctly that I don't need to change any config and that I only expect assists to still place the cursor in the correct place?

**Comment by TimoFreiberg** [comment]
Oh my, this fixes the "select the generated `todo!()`" part of https://github.com/rust-analyzer/rust-analyzer/issues/3639 :tada:

**Comment by oblitum** [comment]
For me, checking actions when cursor is over `foo` at:

```rust
fn main() {
    foo();
}
```

Gives `Add function` action, which when triggered, generates a stub like:


```rust
fn main() {
    foo();
}
fn foo() {
    todo!()
}
```

I can see from statusline that I enter an coc snippet session, but it's not useful because my cursor is at the end of the code, and there's no placeholder to jump to.

Not sure whether this is what I should be testing here.

**Comment by oblitum** [comment]
Happens with `mini.vim` as:

```vim
set runtimepath^=~/.vim/plugged/coc.nvim
colorscheme peachpuff
nmap <silent> <leader>cA <Plug>(coc-codeaction)
vmap <silent> <leader>cA <Plug>(coc-codeaction-selected)
```

**Comment by fannheyward** [comment]
@oblitum do you use the stable or nightly release? stable release will add function foo but without jumping into it. nightly release will bring you into the foo function, and select `todo!()` in snippet mode.

https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/dev/lsp-extensions.md#snippettextedit

**Comment by oblitum** [comment]
I've tests with this pull + rust-analyzer nightly [42dd0ce](https://github.com/rust-analyzer/rust-analyzer/commit/42dd0ce51ffee1dbfc58be7ebb0861aa2331b9cc).

**Comment by fannheyward** [comment]
Yes, it's the latest nightly release. This snippet textEdit feature is new in rust-analyzer.

**Comment by fannheyward** [comment]
@TimoFreiberg how do you get `Generating a function in another module` action?

**Comment by TimoFreiberg** [comment]
By writing `mod foo;` in some rust file, when the `foo.rs` doesn't exist yet. Then just placing the cursor on `foo` and trigger `(coc-codeaction)`

**Comment by fannheyward** [comment]
@TimoFreiberg yes, this will trigger `Create module` action, create `foo.rs` file, but there is no `generates the function`, nothing in foo.rs.

**Comment by TimoFreiberg** [comment]
Oh shit, I misread.
In that example case, when `foo.rs` exists, writing `foo::bar();` in the old file should offer to generate `fn bar() { todo!() }` in `foo.rs`.

**Comment by fannheyward** [comment]
@TimoFreiberg reproduced.

**Comment by fannheyward** [comment]
@TimoFreiberg  Tested with VSCode + RA, will fail to generate function for this example case. https://github.com/rust-analyzer/rust-analyzer/issues/4551

**Comment by oblitum** [comment]
Sorry folks but I couldn't make it work like expected on my side, even with this branch compiled and latest rust-analyzer nightly. Jump to place holder doesn't work. Now on latest coc.nvim things got a bit more non intuitive because it's not showing coc actions for current line anymore and actions for buffer by default, so to even make the create function action to show I have to use coc action with selection.

**Comment by fannheyward** [comment]
@oblitum yes, `coc-codeaction` was changed to buffer only, you can use `coc-codeaction-line` https://github.com/neoclide/coc.nvim/commit/d79251577df0bfb485ceb3f816f2eb2e8d58b9ad

**Comment by fannheyward** [comment]
@TimoFreiberg make a fix for generating function issue

**Comment by TimoFreiberg** [comment]
Now the closing brace of the generated function gets selected instead of the `todo!()`

Expected:
```
fn foo() {
    |todo!()|
}
```

Actual:
```
fn foo() {
   todo!()]
|}|
```

**Comment by oblitum** [comment]
This is the behavior I reported.

**Pull request merged**
