### PR TITLE
feat: range hover

### LINKED ISSUE #836: Range hover support
> the problem is I did find a better way to make Range hover work with nnoremap K. Do you have any ideas?

You're using [getSelectedRange](https://github.com/fannheyward/coc-rust-analyzer/commit/f6092a7a30b9ecd352ebef93479c07c6064cbc79#diff-25d66d74617fe2e23d7946bd6e3ba95640ab1b9bc8947445d604fc271c7c1f12R70) while [expecting Vim to be in visual mode](https://github.com/fannheyward/coc-rust-analyzer/commit/f6092a7a30b9ecd352ebef93479c07c6064cbc79#diff-25d66d74617fe2e23d7946bd6e3ba95640ab1b9bc8947445d604fc271c7c1f12R68), however `:<C-U>` kind of mappings (e.g. `xmap <Plug>(coc-codeaction-selected)`) exit visual mode before executing the range and therefore that check will not pass.

While you could use `<cmd>` mappings to avoid exiting visual mode, exiting is needed to get the visual mode range with `'<` and `'>` like [here](https://github.com/neoclide/coc.nvim/blob/c805bf0a63c67936cf9475cb47cd078280959071/src/workspace.ts#L648) (as far as I'm aware it's not possible to do that while staying in visual mode, you have to exit it first for those marks' positions to be updated).

So, in short, the solution is to make the mapping work like `xmap <Plug>(coc-codeaction-selected)` where you'll detect `visualmode()` *when* the mapping is triggered, not after. [Here's the doCodeAction code](https://github.com/neoclide/coc.nvim/blob/c805bf0a63c67936cf9475cb47cd078280959071/src/handler/codeActions.ts#L85) for reference and you'll see that it fetches the visual range using the marks' positions as mentioned.

_Originally posted by @resolritter in https://github.com/fannheyward/coc-rust-analyzer/issues/256#issuecomment-894335034_

### PR DESCRIPTION
**Pull request by fannheyward**
close #836
FYI #256

### CODE REVIEW

**Review by resolritter — CHANGES_REQUESTED** [review]

**Comment by resolritter** [comment]
With the adjustments from https://github.com/fannheyward/coc-rust-analyzer/pull/839#discussion_r687004739 I was able to execute it:

`vnoremap <silent> <buffer> K <cmd>call CocActionAsync('doHover')<CR>`

**Comment by resolritter** [comment]
Unrelated to this PR, but tsserver was complaining about `Property 'markdown' is missing in LanguageClientOptions` when I opened that `src/client.ts` file. In [coc.nvim master it's optional](https://github.com/neoclide/coc.nvim/blob/c49acf35d8c32c16e1f14ab056a15308e0751688/src/language-client/client.ts#L737) so maybe the typings here are outdated? In any case feel free to disregard this

**Comment by fannheyward** [comment]
> Property 'markdown' is missing in LanguageClientOptions

You can ignore this, this has been fixed already but the typings was not published https://github.com/neoclide/coc.nvim/pull/3232.

**Comment by fannheyward** [comment]
Thank you @resolritter , range hover is working in my tests, this can't be here without your help, thank you!

**Review by resolritter — APPROVED** [review]
Thanks for this :-)

**Comment by TonalidadeHidrica** [comment]
Thanks for your information.  I removed the lines I wrote above and replaced with yours, but it does not still show up.  Also, I have the latest stable `rust-analyzer` build, as described at the bottom of my last comment.

**Pull request merged**
